import { db } from "./db";

const exercises = [
  // Chest
  { name: "Bench Press", muscle_group: "chest" },
  { name: "Incline Bench Press", muscle_group: "chest" },
  { name: "Decline Bench Press", muscle_group: "chest" },
  { name: "Dumbbell Bench Press", muscle_group: "chest" },
  { name: "Incline Dumbbell Press", muscle_group: "chest" },
  { name: "Decline Dumbbell Press", muscle_group: "chest" },
  { name: "Chest Fly", muscle_group: "chest" },
  { name: "Incline Dumbbell Fly", muscle_group: "chest" },
  { name: "Cable Crossover", muscle_group: "chest" },
  { name: "Low Cable Crossover", muscle_group: "chest" },
  { name: "High Cable Crossover", muscle_group: "chest" },
  { name: "Push-Ups", muscle_group: "chest" },
  { name: "Wide Push-Ups", muscle_group: "chest" },
  { name: "Diamond Push-Ups", muscle_group: "chest" },
  { name: "Decline Push-Ups", muscle_group: "chest" },
  { name: "Incline Push-Ups", muscle_group: "chest" },
  { name: "Clap Push-Ups", muscle_group: "chest" },
  { name: "Dips (Chest)", muscle_group: "chest" },
  { name: "Machine Chest Press", muscle_group: "chest" },
  { name: "Pec Deck", muscle_group: "chest" },
  { name: "Svend Press", muscle_group: "chest" },
  { name: "Landmine Press", muscle_group: "chest" },
  { name: "Floor Press", muscle_group: "chest" },
  { name: "Squeeze Press", muscle_group: "chest" },
  { name: "Pullover", muscle_group: "chest" },

  // Back
  { name: "Deadlift", muscle_group: "back" },
  { name: "Conventional Deadlift", muscle_group: "back" },
  { name: "Sumo Deadlift", muscle_group: "back" },
  { name: "Romanian Deadlift", muscle_group: "back" },
  { name: "Stiff-Leg Deadlift", muscle_group: "back" },
  { name: "Deficit Deadlift", muscle_group: "back" },
  { name: "Rack Pull", muscle_group: "back" },
  { name: "Pull-Ups", muscle_group: "back" },
  { name: "Wide Grip Pull-Ups", muscle_group: "back" },
  { name: "Close Grip Pull-Ups", muscle_group: "back" },
  { name: "Chin-Ups", muscle_group: "back" },
  { name: "Neutral Grip Pull-Ups", muscle_group: "back" },
  { name: "Weighted Pull-Ups", muscle_group: "back" },
  { name: "Assisted Pull-Ups", muscle_group: "back" },
  { name: "Lat Pulldown", muscle_group: "back" },
  { name: "Wide Grip Lat Pulldown", muscle_group: "back" },
  { name: "Close Grip Lat Pulldown", muscle_group: "back" },
  { name: "Reverse Grip Lat Pulldown", muscle_group: "back" },
  { name: "Single Arm Lat Pulldown", muscle_group: "back" },
  { name: "Straight Arm Pulldown", muscle_group: "back" },
  { name: "Barbell Row", muscle_group: "back" },
  { name: "Pendlay Row", muscle_group: "back" },
  { name: "Yates Row", muscle_group: "back" },
  { name: "Dumbbell Row", muscle_group: "back" },
  { name: "Single Arm Dumbbell Row", muscle_group: "back" },
  { name: "Chest Supported Row", muscle_group: "back" },
  { name: "Incline Dumbbell Row", muscle_group: "back" },
  { name: "Seated Cable Row", muscle_group: "back" },
  { name: "Wide Grip Cable Row", muscle_group: "back" },
  { name: "Face Pull", muscle_group: "back" },
  { name: "T-Bar Row", muscle_group: "back" },
  { name: "Meadows Row", muscle_group: "back" },
  { name: "Kroc Row", muscle_group: "back" },
  { name: "Inverted Row", muscle_group: "back" },
  { name: "Machine Row", muscle_group: "back" },
  { name: "Hammer Strength Row", muscle_group: "back" },
  { name: "Seal Row", muscle_group: "back" },
  { name: "Helms Row", muscle_group: "back" },
  { name: "Good Morning", muscle_group: "back" },
  { name: "Back Extension", muscle_group: "back" },
  { name: "Hyperextension", muscle_group: "back" },
  { name: "Reverse Hyperextension", muscle_group: "back" },
  { name: "Superman", muscle_group: "back" },
  { name: "Shrugs", muscle_group: "back" },
  { name: "Dumbbell Shrugs", muscle_group: "back" },
  { name: "Barbell Shrugs", muscle_group: "back" },
  { name: "Trap Bar Shrugs", muscle_group: "back" },

  // Shoulders
  { name: "Overhead Press", muscle_group: "shoulders" },
  { name: "Military Press", muscle_group: "shoulders" },
  { name: "Seated Overhead Press", muscle_group: "shoulders" },
  { name: "Push Press", muscle_group: "shoulders" },
  { name: "Behind the Neck Press", muscle_group: "shoulders" },
  { name: "Dumbbell Shoulder Press", muscle_group: "shoulders" },
  { name: "Seated Dumbbell Press", muscle_group: "shoulders" },
  { name: "Arnold Press", muscle_group: "shoulders" },
  { name: "Landmine Press", muscle_group: "shoulders" },
  { name: "Z Press", muscle_group: "shoulders" },
  { name: "Viking Press", muscle_group: "shoulders" },
  { name: "Machine Shoulder Press", muscle_group: "shoulders" },
  { name: "Smith Machine Shoulder Press", muscle_group: "shoulders" },
  { name: "Lateral Raise", muscle_group: "shoulders" },
  { name: "Dumbbell Lateral Raise", muscle_group: "shoulders" },
  { name: "Cable Lateral Raise", muscle_group: "shoulders" },
  { name: "Machine Lateral Raise", muscle_group: "shoulders" },
  { name: "Leaning Lateral Raise", muscle_group: "shoulders" },
  { name: "Front Raise", muscle_group: "shoulders" },
  { name: "Dumbbell Front Raise", muscle_group: "shoulders" },
  { name: "Barbell Front Raise", muscle_group: "shoulders" },
  { name: "Cable Front Raise", muscle_group: "shoulders" },
  { name: "Plate Front Raise", muscle_group: "shoulders" },
  { name: "Rear Delt Fly", muscle_group: "shoulders" },
  { name: "Reverse Pec Deck", muscle_group: "shoulders" },
  { name: "Bent Over Rear Delt Fly", muscle_group: "shoulders" },
  { name: "Cable Rear Delt Fly", muscle_group: "shoulders" },
  { name: "Face Pull", muscle_group: "shoulders" },
  { name: "Upright Row", muscle_group: "shoulders" },
  { name: "Barbell Upright Row", muscle_group: "shoulders" },
  { name: "Dumbbell Upright Row", muscle_group: "shoulders" },
  { name: "Cable Upright Row", muscle_group: "shoulders" },
  { name: "Lu Raise", muscle_group: "shoulders" },
  { name: "Bradford Press", muscle_group: "shoulders" },
  { name: "Bus Driver", muscle_group: "shoulders" },
  { name: "Scarecrow", muscle_group: "shoulders" },
  { name: "Around the World", muscle_group: "shoulders" },
  { name: "Handstand Push-Ups", muscle_group: "shoulders" },
  { name: "Pike Push-Ups", muscle_group: "shoulders" },

  // Biceps
  { name: "Barbell Curl", muscle_group: "biceps" },
  { name: "EZ Bar Curl", muscle_group: "biceps" },
  { name: "Dumbbell Curl", muscle_group: "biceps" },
  { name: "Alternating Dumbbell Curl", muscle_group: "biceps" },
  { name: "Hammer Curl", muscle_group: "biceps" },
  { name: "Cross Body Hammer Curl", muscle_group: "biceps" },
  { name: "Concentration Curl", muscle_group: "biceps" },
  { name: "Preacher Curl", muscle_group: "biceps" },
  { name: "EZ Bar Preacher Curl", muscle_group: "biceps" },
  { name: "Dumbbell Preacher Curl", muscle_group: "biceps" },
  { name: "Spider Curl", muscle_group: "biceps" },
  { name: "Incline Dumbbell Curl", muscle_group: "biceps" },
  { name: "Decline Dumbbell Curl", muscle_group: "biceps" },
  { name: "Cable Curl", muscle_group: "biceps" },
  { name: "Cable Rope Curl", muscle_group: "biceps" },
  { name: "High Cable Curl", muscle_group: "biceps" },
  { name: "Bayesian Curl", muscle_group: "biceps" },
  { name: "Machine Curl", muscle_group: "biceps" },
  { name: "Reverse Curl", muscle_group: "biceps" },
  { name: "Zottman Curl", muscle_group: "biceps" },
  { name: "Drag Curl", muscle_group: "biceps" },
  { name: "21s", muscle_group: "biceps" },
  { name: "Cheat Curl", muscle_group: "biceps" },
  { name: "Waiter Curl", muscle_group: "biceps" },
  { name: "Prone Incline Curl", muscle_group: "biceps" },

  // Triceps
  { name: "Close Grip Bench Press", muscle_group: "triceps" },
  { name: "Skull Crushers", muscle_group: "triceps" },
  { name: "EZ Bar Skull Crushers", muscle_group: "triceps" },
  { name: "Dumbbell Skull Crushers", muscle_group: "triceps" },
  { name: "Tricep Dips", muscle_group: "triceps" },
  { name: "Bench Dips", muscle_group: "triceps" },
  { name: "Weighted Dips", muscle_group: "triceps" },
  { name: "Tricep Pushdown", muscle_group: "triceps" },
  { name: "Rope Pushdown", muscle_group: "triceps" },
  { name: "V-Bar Pushdown", muscle_group: "triceps" },
  { name: "Straight Bar Pushdown", muscle_group: "triceps" },
  { name: "Single Arm Pushdown", muscle_group: "triceps" },
  { name: "Reverse Grip Pushdown", muscle_group: "triceps" },
  { name: "Overhead Tricep Extension", muscle_group: "triceps" },
  { name: "Dumbbell Overhead Extension", muscle_group: "triceps" },
  { name: "Cable Overhead Extension", muscle_group: "triceps" },
  { name: "EZ Bar Overhead Extension", muscle_group: "triceps" },
  { name: "Single Arm Overhead Extension", muscle_group: "triceps" },
  { name: "Tricep Kickback", muscle_group: "triceps" },
  { name: "Cable Kickback", muscle_group: "triceps" },
  { name: "JM Press", muscle_group: "triceps" },
  { name: "Tate Press", muscle_group: "triceps" },
  { name: "French Press", muscle_group: "triceps" },
  { name: "Diamond Push-Ups", muscle_group: "triceps" },
  { name: "Close Grip Push-Ups", muscle_group: "triceps" },
  { name: "Bodyweight Tricep Extension", muscle_group: "triceps" },
  { name: "Machine Tricep Extension", muscle_group: "triceps" },
  { name: "Dip Machine", muscle_group: "triceps" },

  // Quadriceps
  { name: "Squat", muscle_group: "quadriceps" },
  { name: "Back Squat", muscle_group: "quadriceps" },
  { name: "Front Squat", muscle_group: "quadriceps" },
  { name: "High Bar Squat", muscle_group: "quadriceps" },
  { name: "Low Bar Squat", muscle_group: "quadriceps" },
  { name: "Pause Squat", muscle_group: "quadriceps" },
  { name: "Box Squat", muscle_group: "quadriceps" },
  { name: "Safety Bar Squat", muscle_group: "quadriceps" },
  { name: "Zercher Squat", muscle_group: "quadriceps" },
  { name: "Goblet Squat", muscle_group: "quadriceps" },
  { name: "Dumbbell Squat", muscle_group: "quadriceps" },
  { name: "Hack Squat", muscle_group: "quadriceps" },
  { name: "Machine Hack Squat", muscle_group: "quadriceps" },
  { name: "Barbell Hack Squat", muscle_group: "quadriceps" },
  { name: "V-Squat", muscle_group: "quadriceps" },
  { name: "Pendulum Squat", muscle_group: "quadriceps" },
  { name: "Belt Squat", muscle_group: "quadriceps" },
  { name: "Smith Machine Squat", muscle_group: "quadriceps" },
  { name: "Leg Press", muscle_group: "quadriceps" },
  { name: "Wide Stance Leg Press", muscle_group: "quadriceps" },
  { name: "Narrow Stance Leg Press", muscle_group: "quadriceps" },
  { name: "Single Leg Press", muscle_group: "quadriceps" },
  { name: "Leg Extension", muscle_group: "quadriceps" },
  { name: "Single Leg Extension", muscle_group: "quadriceps" },
  { name: "Lunge", muscle_group: "quadriceps" },
  { name: "Walking Lunge", muscle_group: "quadriceps" },
  { name: "Reverse Lunge", muscle_group: "quadriceps" },
  { name: "Barbell Lunge", muscle_group: "quadriceps" },
  { name: "Dumbbell Lunge", muscle_group: "quadriceps" },
  { name: "Bulgarian Split Squat", muscle_group: "quadriceps" },
  { name: "Dumbbell Bulgarian Split Squat", muscle_group: "quadriceps" },
  { name: "Barbell Bulgarian Split Squat", muscle_group: "quadriceps" },
  { name: "Split Squat", muscle_group: "quadriceps" },
  { name: "Step-Up", muscle_group: "quadriceps" },
  { name: "Dumbbell Step-Up", muscle_group: "quadriceps" },
  { name: "Barbell Step-Up", muscle_group: "quadriceps" },
  { name: "Sissy Squat", muscle_group: "quadriceps" },
  { name: "Pistol Squat", muscle_group: "quadriceps" },
  { name: "Wall Sit", muscle_group: "quadriceps" },
  { name: "Cyclist Squat", muscle_group: "quadriceps" },
  { name: "Heel Elevated Squat", muscle_group: "quadriceps" },
  { name: "Spanish Squat", muscle_group: "quadriceps" },

  // Hamstrings
  { name: "Romanian Deadlift", muscle_group: "hamstrings" },
  { name: "Dumbbell Romanian Deadlift", muscle_group: "hamstrings" },
  { name: "Single Leg Romanian Deadlift", muscle_group: "hamstrings" },
  { name: "Stiff-Leg Deadlift", muscle_group: "hamstrings" },
  { name: "Good Morning", muscle_group: "hamstrings" },
  { name: "Seated Good Morning", muscle_group: "hamstrings" },
  { name: "Leg Curl", muscle_group: "hamstrings" },
  { name: "Lying Leg Curl", muscle_group: "hamstrings" },
  { name: "Seated Leg Curl", muscle_group: "hamstrings" },
  { name: "Standing Leg Curl", muscle_group: "hamstrings" },
  { name: "Single Leg Curl", muscle_group: "hamstrings" },
  { name: "Nordic Curl", muscle_group: "hamstrings" },
  { name: "Nordic Hamstring Curl", muscle_group: "hamstrings" },
  { name: "Glute Ham Raise", muscle_group: "hamstrings" },
  { name: "Glute Ham Developer", muscle_group: "hamstrings" },
  { name: "Cable Pull Through", muscle_group: "hamstrings" },
  { name: "Kettlebell Swing", muscle_group: "hamstrings" },
  { name: "Hip Hinge", muscle_group: "hamstrings" },
  { name: "Slider Leg Curl", muscle_group: "hamstrings" },
  { name: "Swiss Ball Leg Curl", muscle_group: "hamstrings" },
  { name: "Inverse Leg Curl", muscle_group: "hamstrings" },

  // Glutes
  { name: "Hip Thrust", muscle_group: "glutes" },
  { name: "Barbell Hip Thrust", muscle_group: "glutes" },
  { name: "Dumbbell Hip Thrust", muscle_group: "glutes" },
  { name: "Single Leg Hip Thrust", muscle_group: "glutes" },
  { name: "Banded Hip Thrust", muscle_group: "glutes" },
  { name: "Smith Machine Hip Thrust", muscle_group: "glutes" },
  { name: "Glute Bridge", muscle_group: "glutes" },
  { name: "Single Leg Glute Bridge", muscle_group: "glutes" },
  { name: "Weighted Glute Bridge", muscle_group: "glutes" },
  { name: "Frog Pump", muscle_group: "glutes" },
  { name: "Cable Kickback", muscle_group: "glutes" },
  { name: "Glute Kickback", muscle_group: "glutes" },
  { name: "Donkey Kick", muscle_group: "glutes" },
  { name: "Fire Hydrant", muscle_group: "glutes" },
  { name: "Clamshell", muscle_group: "glutes" },
  { name: "Cable Pull Through", muscle_group: "glutes" },
  { name: "Romanian Deadlift", muscle_group: "glutes" },
  { name: "Sumo Deadlift", muscle_group: "glutes" },
  { name: "Sumo Squat", muscle_group: "glutes" },
  { name: "Wide Stance Squat", muscle_group: "glutes" },
  { name: "Curtsy Lunge", muscle_group: "glutes" },
  { name: "Lateral Lunge", muscle_group: "glutes" },
  { name: "Step-Up", muscle_group: "glutes" },
  { name: "Reverse Hyperextension", muscle_group: "glutes" },
  { name: "45 Degree Back Extension", muscle_group: "glutes" },
  { name: "Glute Focused Back Extension", muscle_group: "glutes" },
  { name: "Cable Hip Abduction", muscle_group: "glutes" },
  { name: "Machine Hip Abduction", muscle_group: "glutes" },
  { name: "Banded Squat Walk", muscle_group: "glutes" },
  { name: "Monster Walk", muscle_group: "glutes" },
  { name: "Deficit Reverse Lunge", muscle_group: "glutes" },

  // Calves
  { name: "Standing Calf Raise", muscle_group: "calves" },
  { name: "Machine Standing Calf Raise", muscle_group: "calves" },
  { name: "Smith Machine Calf Raise", muscle_group: "calves" },
  { name: "Dumbbell Calf Raise", muscle_group: "calves" },
  { name: "Barbell Calf Raise", muscle_group: "calves" },
  { name: "Single Leg Calf Raise", muscle_group: "calves" },
  { name: "Seated Calf Raise", muscle_group: "calves" },
  { name: "Machine Seated Calf Raise", muscle_group: "calves" },
  { name: "Leg Press Calf Raise", muscle_group: "calves" },
  { name: "Donkey Calf Raise", muscle_group: "calves" },
  { name: "Hack Squat Calf Raise", muscle_group: "calves" },
  { name: "Tibialis Raise", muscle_group: "calves" },
  { name: "Toe Raise", muscle_group: "calves" },
  { name: "Jump Rope", muscle_group: "calves" },
  { name: "Box Jump", muscle_group: "calves" },

  // Core / Abs
  { name: "Crunch", muscle_group: "core" },
  { name: "Weighted Crunch", muscle_group: "core" },
  { name: "Cable Crunch", muscle_group: "core" },
  { name: "Machine Crunch", muscle_group: "core" },
  { name: "Reverse Crunch", muscle_group: "core" },
  { name: "Bicycle Crunch", muscle_group: "core" },
  { name: "Sit-Up", muscle_group: "core" },
  { name: "Weighted Sit-Up", muscle_group: "core" },
  { name: "Decline Sit-Up", muscle_group: "core" },
  { name: "V-Up", muscle_group: "core" },
  { name: "Tuck Up", muscle_group: "core" },
  { name: "Leg Raise", muscle_group: "core" },
  { name: "Lying Leg Raise", muscle_group: "core" },
  { name: "Hanging Leg Raise", muscle_group: "core" },
  { name: "Hanging Knee Raise", muscle_group: "core" },
  { name: "Captain's Chair Leg Raise", muscle_group: "core" },
  { name: "Toes to Bar", muscle_group: "core" },
  { name: "Plank", muscle_group: "core" },
  { name: "Weighted Plank", muscle_group: "core" },
  { name: "Side Plank", muscle_group: "core" },
  { name: "Plank to Push-Up", muscle_group: "core" },
  { name: "Body Saw", muscle_group: "core" },
  { name: "Dead Bug", muscle_group: "core" },
  { name: "Bird Dog", muscle_group: "core" },
  { name: "Hollow Body Hold", muscle_group: "core" },
  { name: "Ab Wheel Rollout", muscle_group: "core" },
  { name: "Barbell Rollout", muscle_group: "core" },
  { name: "Stability Ball Rollout", muscle_group: "core" },
  { name: "Mountain Climber", muscle_group: "core" },
  { name: "Russian Twist", muscle_group: "core" },
  { name: "Weighted Russian Twist", muscle_group: "core" },
  { name: "Medicine Ball Russian Twist", muscle_group: "core" },
  { name: "Woodchop", muscle_group: "core" },
  { name: "Cable Woodchop", muscle_group: "core" },
  { name: "Pallof Press", muscle_group: "core" },
  { name: "Cable Pallof Press", muscle_group: "core" },
  { name: "Band Pallof Press", muscle_group: "core" },
  { name: "L-Sit", muscle_group: "core" },
  { name: "Dragon Flag", muscle_group: "core" },
  { name: "Landmine Rotation", muscle_group: "core" },
  { name: "Landmine 180s", muscle_group: "core" },
  { name: "Suitcase Carry", muscle_group: "core" },
  { name: "Farmer's Walk", muscle_group: "core" },
  { name: "Turkish Get-Up", muscle_group: "core" },
  { name: "Windmill", muscle_group: "core" },
  { name: "Side Bend", muscle_group: "core" },
  { name: "Dumbbell Side Bend", muscle_group: "core" },
  { name: "Cable Side Bend", muscle_group: "core" },
  { name: "Hanging Windshield Wiper", muscle_group: "core" },
  { name: "Lying Windshield Wiper", muscle_group: "core" },
  { name: "Toe Touch", muscle_group: "core" },
  { name: "Flutter Kick", muscle_group: "core" },
  { name: "Scissor Kick", muscle_group: "core" },

  // Forearms
  { name: "Wrist Curl", muscle_group: "forearms" },
  { name: "Barbell Wrist Curl", muscle_group: "forearms" },
  { name: "Dumbbell Wrist Curl", muscle_group: "forearms" },
  { name: "Reverse Wrist Curl", muscle_group: "forearms" },
  { name: "Behind the Back Wrist Curl", muscle_group: "forearms" },
  { name: "Wrist Roller", muscle_group: "forearms" },
  { name: "Farmer's Walk", muscle_group: "forearms" },
  { name: "Dead Hang", muscle_group: "forearms" },
  { name: "Plate Pinch", muscle_group: "forearms" },
  { name: "Towel Pull-Up", muscle_group: "forearms" },
  { name: "Fat Grip Training", muscle_group: "forearms" },
  { name: "Gripper", muscle_group: "forearms" },
  { name: "Hand Gripper", muscle_group: "forearms" },
  { name: "Reverse Curl", muscle_group: "forearms" },
  { name: "Hammer Curl", muscle_group: "forearms" },
  { name: "Zottman Curl", muscle_group: "forearms" },
  { name: "Wrist Extension", muscle_group: "forearms" },
  { name: "Pronation/Supination", muscle_group: "forearms" },
  { name: "Finger Curl", muscle_group: "forearms" },
  { name: "Radial Deviation", muscle_group: "forearms" },
  { name: "Ulnar Deviation", muscle_group: "forearms" },

  // Full Body / Compound
  { name: "Clean", muscle_group: "full_body" },
  { name: "Power Clean", muscle_group: "full_body" },
  { name: "Hang Clean", muscle_group: "full_body" },
  { name: "Clean and Jerk", muscle_group: "full_body" },
  { name: "Clean and Press", muscle_group: "full_body" },
  { name: "Snatch", muscle_group: "full_body" },
  { name: "Power Snatch", muscle_group: "full_body" },
  { name: "Hang Snatch", muscle_group: "full_body" },
  { name: "Thruster", muscle_group: "full_body" },
  { name: "Barbell Thruster", muscle_group: "full_body" },
  { name: "Dumbbell Thruster", muscle_group: "full_body" },
  { name: "Kettlebell Thruster", muscle_group: "full_body" },
  { name: "Wall Ball", muscle_group: "full_body" },
  { name: "Burpee", muscle_group: "full_body" },
  { name: "Burpee Box Jump", muscle_group: "full_body" },
  { name: "Burpee Pull-Up", muscle_group: "full_body" },
  { name: "Man Maker", muscle_group: "full_body" },
  { name: "Devil Press", muscle_group: "full_body" },
  { name: "Turkish Get-Up", muscle_group: "full_body" },
  { name: "Kettlebell Swing", muscle_group: "full_body" },
  { name: "Russian Kettlebell Swing", muscle_group: "full_body" },
  { name: "American Kettlebell Swing", muscle_group: "full_body" },
  { name: "Kettlebell Snatch", muscle_group: "full_body" },
  { name: "Kettlebell Clean", muscle_group: "full_body" },
  { name: "Kettlebell Clean and Press", muscle_group: "full_body" },
  { name: "Farmer's Walk", muscle_group: "full_body" },
  { name: "Farmer's Carry", muscle_group: "full_body" },
  { name: "Trap Bar Carry", muscle_group: "full_body" },
  { name: "Yoke Walk", muscle_group: "full_body" },
  { name: "Sandbag Carry", muscle_group: "full_body" },
  { name: "Atlas Stone", muscle_group: "full_body" },
  { name: "Sled Push", muscle_group: "full_body" },
  { name: "Sled Pull", muscle_group: "full_body" },
  { name: "Prowler Push", muscle_group: "full_body" },
  { name: "Tire Flip", muscle_group: "full_body" },
  { name: "Battle Ropes", muscle_group: "full_body" },
  { name: "Rope Climb", muscle_group: "full_body" },
  { name: "Bear Crawl", muscle_group: "full_body" },
  { name: "Crab Walk", muscle_group: "full_body" },
  { name: "Inch Worm", muscle_group: "full_body" },
  { name: "Jumping Jack", muscle_group: "full_body" },
  { name: "High Knees", muscle_group: "full_body" },
  { name: "Butt Kicks", muscle_group: "full_body" },
  { name: "Box Jump", muscle_group: "full_body" },
  { name: "Broad Jump", muscle_group: "full_body" },
  { name: "Tuck Jump", muscle_group: "full_body" },
  { name: "Squat Jump", muscle_group: "full_body" },
  { name: "Lunge Jump", muscle_group: "full_body" },
  { name: "Split Jump", muscle_group: "full_body" },
  { name: "Medicine Ball Slam", muscle_group: "full_body" },
  { name: "Medicine Ball Throw", muscle_group: "full_body" },
  { name: "Rowing Machine", muscle_group: "full_body" },
  { name: "Assault Bike", muscle_group: "full_body" },
  { name: "Ski Erg", muscle_group: "full_body" },
  { name: "Elliptical", muscle_group: "full_body" },
  { name: "Swimming", muscle_group: "full_body" },
  { name: "Running", muscle_group: "full_body" },
  { name: "Sprints", muscle_group: "full_body" },
  { name: "Hill Sprints", muscle_group: "full_body" },
  { name: "Stair Climber", muscle_group: "full_body" },
  { name: "Cycling", muscle_group: "full_body" },
  { name: "Jump Rope", muscle_group: "full_body" },
  { name: "Double Unders", muscle_group: "full_body" },

  // Neck
  { name: "Neck Curl", muscle_group: "neck" },
  { name: "Neck Extension", muscle_group: "neck" },
  { name: "Neck Lateral Flexion", muscle_group: "neck" },
  { name: "Neck Rotation", muscle_group: "neck" },
  { name: "Weighted Neck Curl", muscle_group: "neck" },
  { name: "Weighted Neck Extension", muscle_group: "neck" },
  { name: "Neck Harness", muscle_group: "neck" },
  { name: "Neck Bridge", muscle_group: "neck" },
  { name: "Manual Neck Resistance", muscle_group: "neck" },
  { name: "Neck Machine", muscle_group: "neck" },
  { name: "4-Way Neck Machine", muscle_group: "neck" },
  { name: "Shrugs", muscle_group: "neck" },
  { name: "Face Pull", muscle_group: "neck" },

  // Hip Flexors / Adductors / Abductors
  { name: "Hip Flexor Raise", muscle_group: "hip_flexors" },
  { name: "Hanging Hip Flexor Raise", muscle_group: "hip_flexors" },
  { name: "Cable Hip Flexion", muscle_group: "hip_flexors" },
  { name: "Psoas March", muscle_group: "hip_flexors" },
  { name: "Seated Hip Flexion", muscle_group: "hip_flexors" },
  { name: "Hip Adduction", muscle_group: "adductors" },
  { name: "Machine Hip Adduction", muscle_group: "adductors" },
  { name: "Cable Hip Adduction", muscle_group: "adductors" },
  { name: "Copenhagen Plank", muscle_group: "adductors" },
  { name: "Side-Lying Hip Adduction", muscle_group: "adductors" },
  { name: "Sumo Squat", muscle_group: "adductors" },
  { name: "Wide Stance Squat", muscle_group: "adductors" },
  { name: "Hip Abduction", muscle_group: "abductors" },
  { name: "Machine Hip Abduction", muscle_group: "abductors" },
  { name: "Cable Hip Abduction", muscle_group: "abductors" },
  { name: "Side-Lying Hip Abduction", muscle_group: "abductors" },
  { name: "Banded Hip Abduction", muscle_group: "abductors" },
  { name: "Clamshell", muscle_group: "abductors" },
  { name: "Fire Hydrant", muscle_group: "abductors" },
  { name: "Lateral Band Walk", muscle_group: "abductors" },
  { name: "Monster Walk", muscle_group: "abductors" },
];

// Check if exercises already exist
const count = db.query("SELECT COUNT(*) as count FROM exercises").get() as {
  count: number;
};

if (count.count === 0) {
  const stmt = db.prepare(
    "INSERT INTO exercises (name, muscle_group) VALUES (?, ?)",
  );

  for (const exercise of exercises) {
    stmt.run(exercise.name, exercise.muscle_group);
  }

  console.log(`Seeded ${exercises.length} exercises`);
} else {
  console.log("Exercises already seeded");
}
